sudo: required
language: generic
services:
  - docker

before-install:
  - docker build -t kaliprasad409/docker-react -f Dockerfile.dev .
script:
  - docker run kaliprasad409/docker-react npm run test -- --coverage




